### ISSUE TITLE
Feature request: Mach-O support

### ISSUE THREAD

**Issue by comex** [Vector35/dwarf_import#20]
Right now the plugin only supports ELF binaries, but Mach-O binaries can also contain DWARF debug info.  It would be useful to support those as well.

**Comment by rickmark** [comment]
https://pypi.org/project/macholib/

Might be a useful package for parsing of the macho files

**Comment by KyleMiles** [comment]
Closing in favor of https://github.com/Vector35/binaryninja-api/issues/3643 (will resolve Mach-Os with debug info inside them as well).
Please check out our new dwarf parser: https://github.com/Vector35/binaryninja-api/issues/3206#issuecomment-1629342753
