### ISSUE TITLE
Feature: dSYM support

### ISSUE THREAD

**Issue by rickmark** [Vector35/dwarf_import#21]
For macOS platforms dSYM bundles are just pretty wrappers on DWARF files - which you can use with the full path, but difficult from the UI as the file picker does not show the contents of the bundle.

If the selected path is a folder ending `.dSYM` appending the path `Contents/Resources/DWARF/<file>` would be the path for the file.

In another universe it could also be really interesting to provide connection to the files in the python directory as they are lldb extensions that provide additional debugging functionality that can be used

**Comment by KyleMiles** [comment]
Closing in favor of https://github.com/Vector35/binaryninja-api/issues/3643
Please check out our new dwarf parser: https://github.com/Vector35/binaryninja-api/issues/3206#issuecomment-1629342753
