### ISSUE TITLE
Error on processing some linux files for is_valid

### ISSUE THREAD

**Issue by rvrecen** [Vector35/dwarf_import#24]
Unsure what source of this error is, not sure whether this is just outdated or if API in elftools has changed

```
Traceback (most recent call last):
  File "...\binaryninja\plugin.py", line 229, in _default_is_valid
    return is_valid(view_obj)
  File "...plugins\analysis_dwarf\__init__.py", line 106, in is_valid
    return raw and elf and ELFFile(reader).has_dwarf_info()
  File "...site-packages\elftools\elf\elffile.py", line 81, in __init__
    self.stream.seek(0, io.SEEK_END)
TypeError: BinaryReader.seek() takes 2 positional arguments but 3 were given

```

analysis_dwarf is renamed directory of dwarf_import, and this error triggers on loading elf-Linux-x64-bash

[elf-Linux-x64-bash.zip](https://github.com/Vector35/dwarf_import/files/10607609/elf-Linux-x64-bash.zip)

pyelftools==0.28

**Comment by KyleMiles** [comment]
The file you provided does not include any DWARF information, as far as I can tell:

```
elf-Linux-x64-bash: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=3fbc74b2edb4842f494d8dd682ea61c60816eaf1, stripped
```

As a heads up, if you'd like to test it, we just released our new DWARF import plugin (now ships with the product, and automatically parses DWARF when available): https://github.com/Vector35/binaryninja-api/issues/3206#issuecomment-1629342753
