### ISSUE TITLE
Support for pyelftools 0.29 (parsing DWARFv5)

### ISSUE THREAD

**Issue by patacca** [Vector35/dwarf_import#25]
In the latest version of pyelftools they added support for DWARFv5 (see https://github.com/eliben/pyelftools/issues/391) but unfortunately this plugin only uses pyelftools 0.27
Can you please add support for pyelftools 0.29? There are some issues with that which must be solved (see https://github.com/Vector35/dwarf_import/issues/18, https://github.com/Vector35/dwarf_import/issues/24, https://github.com/Vector35/dwarf_import/issues/16)

**Comment by KyleMiles** [comment]
Please try parsing your files with our new DWARF plugin: https://github.com/Vector35/binaryninja-api/issues/3206#issuecomment-1629342753

It uses [gmili](https://github.com/gimli-rs/gimli) under the hood, which should support DWARF 5.
