### ISSUE TITLE
Feature Request: Load DWARF at specific function

### ISSUE THREAD

**Issue by oskarwirga** [Vector35/dwarf_import#27]
A common pain point in my workflow is not being able to use DWARF for very large files (>100MB). Often I only need it for a specific function, as I am ignorant of the DWARF spec, would it be possible to add a feature to only enable loading dwarf at a specific function? Thanks!

**Comment by KyleMiles** [comment]
Sorry, but I don't think this will be possible. For this plugin, we're using an external library to parse the DWARF info and don't have a lot of control over the process. In general, to load "just one function's" worth of info, you still need to parse a lot of the DWARF info.

That said, you should follow [this issue](https://github.com/Vector35/binaryninja-api/issues/3206) so you can get notified when the Rust version of this plugin gets merged (it's significantly faster and should be more accurate as well).
