### ISSUE TITLE
Change print statement

### ISSUE THREAD

**Issue by infinitesteps** [Vector35/dwarf_import#29]
https://github.com/Vector35/dwarf_import/blob/272360a65550ae1e83c651459e6cb44813fa9d20/location_index.py#L178

Should this be sent to the logger instead of printed to stdout? It is kind of annoying headless.

**Comment by psifertex** [comment]
Yeah, and there's a bunch of other locations that probably should be changed too. We're in the process of totally rewriting this plugin though so I don't know that we plan to make a lot of changes to it in the meantime. You're welcome to PR or fork though!  Replacing `print` with `self._logger.debug` should work, just don't have time to test it.

**Comment by KyleMiles** [comment]
Closing this in favor of our new DWARF plugin: https://github.com/gimli-rs/gimli
